[build]
  command = "CI= npm run build"
  publish = "build"

[[headers]]
  for = "/landing.html"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"

[[redirects]]
  from = "/"
  to = "/landing.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
